### ISSUE TITLE
[Question] Generate an HRF library

### ISSUE THREAD

**Issue by zhengchencai** [cvnlab/GLMsingle#158]
Hello,

Thank you for sharing this excellent method. I’m interested in generating an HRF library from the deconvolution results, similar to what is shown in Figure 3a-c of the NSD Data paper. The GitHub repository for the NSD Data paper ([nsddatapaper repo](https://github.com/cvnlab/nsddatapaper)) refers to this [note](https://github.com/cvnlab/nsddatapaper/blob/main/mainfigures/MANIFOLD/MANIFOLD/MANIFOLDnotes.m), but it appears to be empty. I've gone through the three main papers and repositories (TDM, NSD Data paper, and GLMsingle), and it seems that the relevant method is the TDM approach from Kay et al., Nat Methods, 2020 ([TDM repo](https://github.com/cvnlab/TDM), particularly the extracthrfmanifold.m function). May I ask a few questions to ensure I’m using this method correctly?

Is there an function to perform TDM without the bias-corrected EPI intensities? I guess this was the same thing done in the NSD Data paper (Figure 3a-c). My goal is not to validate the method by comparing EPI intensities across modes in the PCA space (like was done in the original TDM paper). I only want to generate an HRF library. 

I’ve completed deconvolution using AFNI, which applies an FIR model similar to what’s used in TDM. Since TDM essentially summarizes representative patterns across all HRFs, am I correct in assuming that it’s acceptable not to follow the exact processing steps in TDM?

In Figure 3a-b of the NSD Data paper, is the result shown after fitting the 2D Gaussian or before? What is the recommended resolution for each axis? Should I smooth the sphere? 

Instead of using R² for voxel selection after the deconvolution, I filtered based on a sufficiently high F-value (considering all FIR basis). Are there any guidelines on how stringent the statistical threshold (R² or F-value) should be to effectively filter out "non-sig" voxels? Specifically, how much might the HRF library be affected by the inclusion of "flat" or "low-amplitude" HRFs in the decomposition? I assume we do not want a main PC just represeting the "flat" or "low-amplitude" HRFs. 

Thank you very much in advance for your insights!

**Comment by kendrickkay** [comment]
Sorry for the delay.

- Regarding the empty note, that is intentional.  The relevant code is at:
  https://github.com/cvnlab/nsddatapaper/blob/main/main/hrf_constructmanifold.m
  https://github.com/cvnlab/nsddatapaper/blob/main/main/hrf_derivecanonicalpcs.m
  https://github.com/cvnlab/nsddatapaper/blob/main/main/hrf_fitspmhrftomanifold.m

- Yes, the TDM approach is the main relevant method.  However, the way in which the NSD dataset used the TDM approach is a bit different from TDM.  NSD does not attempt to fit the early and late components as two separate regressors.  Rather NSD just accepts that any given voxel is going to show a given mixture of early and late and just assumes that a single voxel will just have a single ideal HRF.



> Is there an function to perform TDM without the bias-corrected EPI intensities?

The TDM method doesn't really use the bias-corrected EPI intensities --- it just uses FIR timecourses (where units are in percent BOLD signal change).   It's just the TDM paper uses the bias-corrected EPI intensities to help interpret what the TDM method achieves.


> I’ve completed deconvolution using AFNI, which applies an FIR model similar to what’s used in TDM. Since TDM essentially summarizes representative patterns across all HRFs, am I correct in assuming that it’s acceptable not to follow the exact processing steps in TDM?
> 
Right.  If your goal is to create a HRF distribution (manifold) as used in NSD, then all of the details of TDM don't really matter that much.  I would recommend just reading and following what the NSD paper describes.  (And refer to the code links above.)


> In Figure 3a-b of the NSD Data paper, is the result shown after fitting the 2D Gaussian or before? What is the recommended resolution for each axis? Should I smooth the sphere?
> 
The NSD methods do not actually involve fitting the Gaussian. Instead, points are clicked on the sphere.  (See hrf_constructmanifold.m)

The code referenced above may be idiosyncratic or involve more steps than you may require.  I debated whether to create a standalone general purpose function to aid the derivation of HRF libraries based on other datasets, but I did not know if there was sufficient need in the community.


> Instead of using R² for voxel selection after the deconvolution, I filtered based on a sufficiently high F-value (considering all FIR basis). Are there any guidelines on how stringent the statistical threshold (R² or F-value) should be to effectively filter out "non-sig" voxels? Specifically, how much might the HRF library be affected by the inclusion of "flat" or "low-amplitude" HRFs in the decomposition? I assume we do not want a main PC just represeting the "flat" or "low-amplitude" HRFs.
> 
Yeah, this is an important issue to consider.  I would recommend creating "distributions on the sphere" for different SNR (or p-value) cutoffs.  My hope is that the general distribution is basically invariant (to a degree) across a range of different cutoffs.  If you have a good dataset, this should be the case.  Of course, one needs to actually inspect carefully to know whether this is the case.



See if the code links referenced above clarifies things for you?

Kendrick

**Comment by zhengchencai** [comment]
Thank you very much for the detailed response. Checking the 2D distribution across various thresholds is a great suggestion—I’d also anticipate a more stable distribution after reaching an optimal threshold. This approach might even allow for an automated selection of the threshold.

After going through the code, it seems that _hrf_derivecanonicalpcs.m_ performs PCA on 20,000 HRFs from each of the 8 subjects after filtering out low R² values, and it saves the basis in hrfbasis.mat.

Then, _hrf_constructmanifold.m_, the key script here, constructs the manifold. Essentially, it taks manually defined landmarks on the sphere based on the density projection. Then _constructpathonsphere.m_ generates a path connecting these landmarks along the sphere. This forms the manifold, from which the HRF library can be derived by reconstructing from 3 principal components. Do you calculate the average of density projection and vector-length projection as done in TDM?

![image](https://github.com/user-attachments/assets/f1ba1a5d-5294-401e-af1c-2f21c24a0280)

_hrf_fitspmhrftomanifold.m_ is a demo for fitting the SPM HRF to the HRF library.

If possible, could you share the .mat files used in the three scripts you mentioned? Specifically, GLMdenoise_nsdBASIConoffhrfbasis.mat, GLMdenoise_nsdSIMPLE.mat, and GLMdenoise_nsdSIMPLEFIR.mat. Then I could run through the code in detail to understand more in detail before adapting it for my purposes. However, if this is complex, I can try to work with the examples provided in TDM. I guess the main consideration is to follow your data structure after FIR. 

Thank you once again for this insightful and useful method.

Zhengchen

**Comment by kendrickkay** [comment]
> Do you calculate the average of density projection and vector-length projection as done in TDM?

I don't quite remember.  But the code is there.  I am guessing that I just look at the density of HRFs.


> If possible, could you share the .mat files used in the three scripts you mentioned? Specifically, GLMdenoise_nsdBASIConoffhrfbasis.mat, GLMdenoise_nsdSIMPLE.mat, and GLMdenoise_nsdSIMPLEFIR.mat. Then I could run through the code in detail to understand more in detail before adapting it for my purposes. 
> 

I have prepared these files for you:
https://www.dropbox.com/scl/fo/lyfu8eiqhhzju4voigeeb/AL64YsvqHok6mIo7klMjDBc?rlkey=3tmffq1524r97goqd4q586p1m&dl=0

**Comment by zhengchencai** [comment]
Thank you so much. Will try and share what I will get.

**Comment by zhengchencai** [comment]
Just a quick feedback, with the data you shared I could run the code. Thank you so much.

**Comment by kendrickkay** [comment]
Great. Let me know if you find interesting things
