### ISSUE TITLE
GLMsingle does not produce figures in desired output folder (or at all)

### ISSUE THREAD

**Issue by ramroomh** [cvnlab/GLMsingle#66]
Hi there,

I am using python 3.8.5 on MACOS (test set) and 3.7.4 on my larger dataset on linux.
I downloaded GLMsingle using: 
`pip install git+https://github.com/cvnlab/GLMsingle.git`

In my test set for example, I iter thru 4 runs of a task evoked BOLD dataset for a single participant:

```
import os
import numpy as np
import nibabel as nib
import pandas as pd
from bids import BIDSLayout
from glmsingle.glmsingle import GLM_single

root = /path/to/test/
processed = BIDSLayout(os.path.join(root,'derivatives','iter4'))
stimdur = 4
tr_new = 1
subjects = 'avl001'

def run_1st_level(processed, stimdur, tr_new, subjects):
    ''' Input several runs per subject to perform cross-validation
    in GLMdenoise (step 3 of GLMsingle). Imaging data and event data
    should be appended into separate lists. '''
    # Get all subjects
    data = []
    design = []
    # Loop over subjects
    for sub in subjects:
        # Grab all upsampled and smoothed runs
        bold_runs = processed.get(subject=sub, extension='.nii.gz', suffix='smooth', return_type='filename')
        # Grab all GLMsingle-compatible event files
        eventfiles = processed.get(subject=sub, extension='.csv', suffix='glmsingle', return_type='filename')
        # Append all runs for a single subject session
        # fMRI data
        for run in bold_runs:
            r = nib.load(run).get_fdata().astype(np.float32)
            data.append(r)
        # design matrices
        for event in eventfiles:
            ev = pd.read_csv(event, header=None).to_numpy(dtype='float32')
            design.append(ev)
        # Initialize model
        gs = GLM_single()
        # Name output folders
        metadata = processed.parse_file_entities(bold_runs[0])
        outdir = os.path.join(os.path.dirname(bold_runs[0]), metadata['task'] + '_concat_glmsingle')
        # Run GLMsingle
        results = gs.fit(
        design,
        data,
        stimdur,
        tr_new,
        outputdir=outdir)
        # Clear data
        data.clear()
        design.clear()
```

The script is executed within a 'scripts' folder within a BIDS validated dataset.

I coded in such a way that the output dir should be made inside ...../path/to/test/derivatives/iter4/sub-avl001/ses-avl001/func/ and named 'fearcond_concat_glmsingle'

GLMsingle runs fine, then saves the output of each step as an .npy file (4 in total) in the appropriate output dir as specified. However no figures are made. Instead, a folder called 'GLMestimatesingletrialfigures' is made in the location where the script was executed (in this case, scripts folder). Additionally, these folders are empty.

Let me know if I can provide any additional information.

**Comment by jacob-prince** [comment]
Our apologies for the delay in responding to this issue. 

@ramroomh, the current implementation of Python GLMsingle accepts both `outputdir` and `figuredir` as input arguments. The former is where data outputs (e.g. GLM betas) will be saved, and the latter is where accompanying figures will be saved. You have specified the `outputdir` but not `figuredir` argument. Currently, by default, if no `figuredir` argument is specified, no figure outputs will be saved. I believe the creation of the empty `GLMestimatesingletrialfigures` directory when no input is provided counts as a bug in our current implementation. While I work to resolve it, for the time being I would recommend passing `figuredir = outdir` as an input to your GLMsingle function call - this should provide the outputs you desire. 

@kendrickkay @iancharest, currently if the users passes `figuredir = None`, the empty `GLMestimatesingletrialfigures` directory is still created due to the following lines of code: 

<img width="603" alt="image" src="https://user-images.githubusercontent.com/35503086/211399259-f9022b95-0a65-4280-a3d6-0d26382a9657.png">

In the current MATLAB implementation, it appears that the default behavior is to set `figuredir` to the same as `outputdir` if the user does not provide an input: 

<img width="355" alt="image" src="https://user-images.githubusercontent.com/35503086/211399641-88028ab8-6092-4c00-bbce-38e026c8851a.png">

I will implement a pull request that changes the default Python behavior to match the MATLAB behavior. I don't see any reason why the `GLMestimatesingletrialfigures` bit exists only on the Python side, but not the MATLAB side. Please confirm that this plan is reasonable.

**Comment by kendrickkay** [comment]
The plan sounds totally reasonable to me

**Comment by ramroomh** [comment]
@jacob-prince Thank you for your informative reply! No worries at all.
