### ISSUE TITLE
using existing code for obtaining predicted time series from estimated betas in the model outputs

### ISSUE THREAD

**Issue by vassiki** [cvnlab/GLMsingle#76]
Thanks for developing this incredible resource, it has been a real pleasure to use!

I'm currently working on using the `betasmd` field of the glmsingle model outputs to generate a predicted time series. I have been trying to get the `glm_predictresponses` function from the [OLS module](https://github.com/cvnlab/GLMsingle/blob/main/glmsingle/ols/glm_predictresponses.py) to work for that purpose, but I am looking for some guidance on the arguments that the function is expecting. Specifically, I'm wondering what the `numtimepoints` argument is meant to provide. I am including a description of the arguments I am currently using and their dimensions.

1. `model`: an xyz (collapsed) by time array, where time is the number of unique trials in the experiment, as spit out by glmSingle.
2. `design`: a list of 2d arrays, time by number of conditions, where time is the number of TRs in the experiment. Length of the list is equal to the number of runs in the experiment.
3. `tr`: repetition time used for acquisition of data for the experiment
4. `numtimepoints`: a list of total number of timepoints for each run in the experiment, which is the same as the second axis of each element of the design argument.
5. `dimdata`: left at the default value of 0.

I have also tried to call this function with just one run's worth of trials selected from the model, and the design for just one run as well, with `numtimepoints` modified to contain just one element. I'm wondering if I'm using the right function for my purpose, and whether my understanding of the parameters is correct. Please let me know if providing any other information will be useful.

**Comment by kendrickkay** [comment]
Hi. I'm not sure you need to use glm_predictresponses to do what you are trying to do. It might be easier and more informative to "do it yourself".

This actually came up in a different discussion.  I hope to include an example script that goes over this process.  A very rough draft script is here: https://www.dropbox.com/s/9xs36cjubaae6n8/makepredictedtimeseries.m?dl=0

Basically, all you need to do is to get the HRF selected for a given voxel, and then the betas (response amplitudes), and then just do the convolution and weighted-sum in order to generate the predicted signal time series.


(To answer your question, your specification of numtimepoints is correct.  However, what you specified for 'model' is not right.  If you really wanted to use glm_predictresponses, you 'model' actually needs to have not the "betas" but actually the HRF timecourses....)

**Comment by vassiki** [comment]
Thanks a lot for sharing the script, I'll work on implementing your suggestion. I assumed that the function needed the model spit out by glmsingle since it is looking for the 'betasmd' parameter in line 63 to figure out the dimensions of the responses, but it's good to know what the function is expecting!

**Comment by kendrickkay** [comment]
Yes, if you wanted to use glm_predictresponses, you would have to pass in the "{B C} where B is time x 1 with the HRF that is common to all voxels" version of the <model> input.  And note that you would have to do this separately for each of the 20 different HRFs that might have been used for individual voxels (since different voxels have different HRFs ultimately selected).

**Comment by vassiki** [comment]
Thanks for your response, here's my current implementation in python, it seems to be doing the trick!

```
from glmsingle.hrf.gethrf import getcanonicalhrflibrary
from scipy.signal import convolve

tr = 1
stimdur = 0.15
# results_glmsingle is a python dictionary that contains all 
# four model outputs from glmsingle

hrfs = getcanonicalhrflibrary(stimdur, tr)
assert hrfs.shape[0] == len(set(results_glmsingle['typed']['HRFindex']))

conv_data = []
for n in range(results_glmsingle['typed']['betasmd'].shape[0]):
    hrf_index = results_glmsingle['typed']['HRFindex'][n]
    hrf = hrfs[hrf_index,:]
    ts = results_glmsingle['typed']['betasmd'][n,:]
    conv_ts = convolve(ts, hrf, mode='same')
    conv_data.append(conv_ts)
conv_data = np.array(conv_data)

assert conv_data.shape == results_glmsingle['typed']['betasmd'].shape
```
